

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/batteryService?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: hasan
    password: hasan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

application:
    security:
      jwt:
        secret-key:  bd8f4809-710b-4f60-bbda-233b920b893d
        expiration: 3600
        header: Authorization
        refresh-token:
          expiration: 604800
app:
  client:
    url: http://localhost:3000

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 9090
